# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

if [ -f ~/.exports ]; then
    source ~/.exports
else
    print "404: ~/.exports file not found."
fi

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="af-magic"
ZSH_THEME="powerlevel10k/powerlevel10k"

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

#plugins=(github git lol bundler common-aliases kubectl)
plugins=(github git lol bundler kubectl)
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

pathdirs=(
/opt/local/etc
/opt/local/bin
/opt/local/sbin
$HOME/.bin
$HOME/.local/bin
/usr/local/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/bin
/bin
/usr/sbin
/sbin
$HOME/go/bin
)

for dir in $pathdirs; do
    if [ -d $dir ]; then
        path+=$dir
    fi
done

# User configuration

# # scripting editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='nvim'
export GOPATH="$HOME/go"
# else
#   export EDITOR='mvim'
# fi

# Aliases
alias zshconfig="vim ~/.zshrc"
alias reload!="source ~/.zshrc"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -l'
alias gen_tags='ctags -R -f .tags'
alias gs='git status'
alias gd='git diff'
alias gfa='git fetch --all'
alias be='bundle exec'
alias nrs='npm run start'
alias nrb='npm run build'

# Tmuxinator aliasses
alias tms='tmuxinator start'
alias tme='tmuxinator edit'
alias tmn='tmuxinator new'
#
# # Neovim
alias vim=nvim

# Kubectl
alias kar='kubectl-argo-rollouts'
alias karlr='kubectl-argo-rollouts list rollouts'

#Adds copy and paste for vim
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# Python
alias python='python3'

# Terraform
alias tf='terraform'

# bat
alias cat="bat"

# ToDo
alias todo="vim ~/.todo.md"

export RUBYOPT="-W0"
export ANDROID_HOME="$HOME/development/adt-bundle-mac-x86_64/sdk"
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH="/usr/local/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

test -e "${HOME}/.credentials.sh" && source "${HOME}/.credentials.sh"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

