
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

if [ -f ~/.exports ]; then
    source ~/.exports
else
    print "404: ~/.exports file not found."
fi

export ZSH="/Users/alvaromuhlethaler/.oh-my-zsh"

ZSH_THEME="robbyrussell"

#plugins=(github git lol bundler common-aliases kubectl)
plugins=(github git lol bundler kubectl)
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

pathdirs=(
/opt/local/etc
/opt/local/bin
/opt/local/sbin
$HOME/.bin
$HOME/.local/bin
/usr/local/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/bin
/bin
/usr/sbin
/sbin
)

for dir in $pathdirs; do
    if [ -d $dir ]; then
        path+=$dir
    fi
done

# User configuration

# # scripting editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='nvim'
# else
#   export EDITOR='mvim'
# fi

# Aliases
alias zshconfig="vim ~/.zshrc"
alias reload!="source ~/.zshrc"

#ALIAS
alias busquelo!='grep -r -n'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -l'
alias gen_tags='ctags -R -f .tags'
alias gs='git status'
alias gd='git diff'
alias gfa='git fetch --all'
alias be='bundle exec'
alias nrs='npm run start'
alias nrb='npm run build'

# Tmuxinator aliasses
alias tms='tmuxinator start'
alias tme='tmuxinator edit'
alias tmn='tmuxinator new'
#
# # Neovim
alias vim=nvim

# Kubectl
alias kar='kubectl-argo-rollouts'
alias karlr='kubectl-argo-rollouts list rollouts'

#Adds copy and paste for vim
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# Python
alias python='python3'

# Terraform
alias tf='terraform'

export PATH="/usr/local/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#tmuxinator
#source ~/.bin/tmuxinator.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(/opt/homebrew/bin/brew shellenv)"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/alvaromuhlethaler/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/develop/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/develop/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/develop/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/develop/google-cloud-sdk/completion.zsh.inc"; fi
